apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 2
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      serviceAccountName: registry-sa
      containers:
      - name: app
        image: c0derhin0/adnu-cevas-lamp:app
        ports:
        - containerPort: 80
        envFrom:
          - configMapRef:
              name: db-config
        env:
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: DB_PASS
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: MYSQL_USER
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: MYSQL_PASSWORD
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: app
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP 