apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  DB_HOST: "db-service"
  DB_NAME: "cevasdb"
  # DB_USER, DB_PASS, MYSQL_ROOT_PASSWORD, MYSQL_USER, MYSQL_PASSWORD are now in the secret 'db-secret' 