apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.app.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: test
  template:
    metadata:
      labels:
        app.kubernetes.io/component: test
    spec:
      containers:
      - name: test-container
        image: busybox:musl
        command:
          - tail
          - -f
          - /dev/null
